#!/usr/bin/perl -w

$filename=$ARGV[0];
$maxrank=0;
for($i=0;$i<=9;$i++) {
  $numlines[$i]=0;
}
open(INFILE,"<$filename");
while($inline = <INFILE> ) {
#Detect rank number in a line such as
#[1,1]<stdout>: Basis set start!
#  if(substr($inline,1,1) eq ":") {
   if(substr($inline,0,3) eq "[1,") {
    $ranknum=substr($inline,3,1);
    if($ranknum>$maxrank){
      $maxrank=$ranknum;
    }
    $numlines[$ranknum]++;
#Substring corresponding to e.g.
#Basis set start!
#   $lines[$ranknum][$numlines[$ranknum]]=$inline;
    $lines[$ranknum][$numlines[$ranknum]]=substr($inline,14)
  }
}
close(INFILE);
for($i=0;$i<=$maxrank;$i++) {
  open(OUTFILE,">$filename"."."."$i");
  for($j=1;$j<=$numlines[$i];$j++) {
    print OUTFILE $lines[$i][$j];
  }
  close(OUTFILE);
}
